version: "3"

services:

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=go-graphql-products
      - MYSQL_USER=user
      - MYSQL_PASSWORD=supersecret
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", 'mysqladmin ping -u user -psupersecret']
      interval: 10s
      timeout: 2s
      retries: 10

  products:
    build:
      context: ./products
    image: marceloaguero/go-graphql-products-products:local
    environment:
      - PORT=8091
      - DB_DSN=user:supersecret@tcp(db:3306)
      - DB_NAME=go-graphql-products
    ports:
      - "8091:8091"
    depends_on:
      - db

  providers:
    build:
      context: ./providers
    image: marceloaguero/go-graphql-products-providers:local
    environment:
      - PORT=8092
      - DB_DSN=user:supersecret@tcp(db:3306)
      - DB_NAME=go-graphql-products
    ports:
      - "8092:8092"
    depends_on:
      - db

  #gateway:
  #  image: ghcr.io/movio/bramble
  #  environment:
  #    #- BRAMBLE_SERVICE_LIST=http://products:8091/query http://providers:8092/query
  #    - BRAMBLE_SERVICE_LIST=http://providers:8092/query
  #  ports:
  #    - "8082:8082"
  #    - "8083:8083"
  #    - "9009:9009"
  #  depends_on:
  #    #- products
  #    - providers

volumes:
  db-data:

