// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ProductInput struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Unit        string   `json:"unit"`
	Price       float64  `json:"price"`
	Stock       *float64 `json:"stock,omitempty"`
	IsActive    *bool    `json:"isActive,omitempty"`
}
